# Generated by Django 2.2.4 on 2019-08-06 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0006_auto_20190806_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('documento', models.FileField(upload_to='dictamenes/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True)),
                ('fecha_muestreo', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de muestreo')),
                ('no_registro', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de registro (Orden de Trabajo)')),
                ('registro_campo', models.FileField(blank=True, null=True, upload_to='registros_campo/%Y/%m/%d/', verbose_name='Registro de campo')),
                ('cadena_custodia', models.FileField(blank=True, null=True, upload_to='cadenas_custioda/%Y/%m/%d/', verbose_name='Cadena de custodia')),
                ('resultado', models.FileField(blank=True, null=True, upload_to='resultados/%Y/%m/%d/', verbose_name='Resultados de análisis de laboratorio')),
                ('fecha_resultado', models.DateField(blank=True, null=True, verbose_name='Fecha del resultado de análisis')),
                ('comparacion_color_verdadero', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_turbiedad', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_ph', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_conductividad_electrica', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_coliformes_fecales', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_coliformes_totales', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_arsenico', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_hierro', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_manganeso', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_plomo', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_floururos', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_nitratos', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_sulfatos', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_dureza_total', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('comparacion_solidos_disueltos', models.CharField(choices=[('=', '='), ('<', '<'), ('≥', '≥'), ('≤', '≤')], default='=', max_length=1, verbose_name='.')),
                ('color_verdadero', models.FloatField(blank=True, null=True, verbose_name='Color verdadero (U Pt-Co)')),
                ('turbiedad', models.FloatField(blank=True, null=True, verbose_name='Turbiedad (UTN o equivalente)')),
                ('ph', models.FloatField(blank=True, null=True, verbose_name='pH (unidades de pH)')),
                ('conductividad_electrica', models.FloatField(blank=True, null=True, verbose_name='Conductividad eléctrica (µS/cm)')),
                ('coliformes_fecales', models.FloatField(blank=True, null=True, verbose_name='Coliformes fecales (UFC o NMP)')),
                ('coliformes_totales', models.FloatField(blank=True, null=True, verbose_name='Coliformes totales (UFC o NMP)')),
                ('arsenico', models.FloatField(blank=True, null=True, verbose_name='Arsénico (mg/L)')),
                ('hierro', models.FloatField(blank=True, null=True, verbose_name='Hierro (mg/L)')),
                ('manganeso', models.FloatField(blank=True, null=True, verbose_name='Manganeso (mg/L)')),
                ('plomo', models.FloatField(blank=True, null=True, verbose_name='Plomo (mg/L)')),
                ('floururos', models.FloatField(blank=True, null=True, verbose_name='Fluoruros (mg/L)')),
                ('nitratos', models.FloatField(blank=True, null=True, verbose_name='Nitratos (mg/L)')),
                ('sulfatos', models.FloatField(blank=True, null=True, verbose_name='Sulfatos (mg/L)')),
                ('dureza_total', models.FloatField(blank=True, null=True, verbose_name='Dureza total (CaCO3) (mg/L)')),
                ('solidos_disueltos', models.FloatField(blank=True, null=True, verbose_name='Sólidos disueltos totales (mg/L)')),
                ('validacion', models.CharField(choices=[('Validado', 'Validado'), ('No validado', 'No validado'), ('En espera', 'En espera')], default='En espera', max_length=11, verbose_name='Validación')),
                ('laboratorio', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('dictamen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agua.Dictamen')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.Escuela')),
            ],
        ),
    ]
