# Generated by Django 2.2.4 on 2019-08-06 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamen',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
