# Generated by Django 2.2.4 on 2019-08-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0002_auto_20190806_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analisis',
            old_name='laboratorio',
            new_name='aboratorio',
        ),
        migrations.AlterField(
            model_name='analisis',
            name='validacion',
            field=models.BooleanField(default=False),
        ),
    ]
