# Generated by Django 2.2.4 on 2019-08-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidad',
            old_name='numero',
            new_name='partida',
        ),
    ]
