# Generated by Django 2.2.4 on 2019-08-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0003_auto_20190805_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
