# Generated by Django 2.2.4 on 2019-08-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0004_region_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, unique=True),
        ),
    ]
