# Generated by Django 2.2.4 on 2019-08-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0005_escuela_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidadconvocatoria',
            old_name='escuelas_asignadas',
            new_name='escuelas_contractuadas',
        ),
        migrations.AddField(
            model_name='entidad',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='entidadconvocatoria',
            name='escuelas_sustituidas',
            field=models.IntegerField(default=0),
        ),
    ]
