# Generated by Django 2.2.4 on 2019-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0008_auto_20190806_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
