# Generated by Django 2.2.4 on 2019-08-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0009_auto_20190813_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadconvocatoria',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad', to='escuelas.Entidad'),
        ),
    ]
