# Generated by Django 2.2.4 on 2019-08-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0013_auto_20190816_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='lista',
        ),
    ]
