# Generated by Django 2.2.4 on 2019-08-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0015_auto_20190816_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='lista',
        ),
        migrations.AddField(
            model_name='oficio',
            name='entidad_convocatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escuelas.EntidadConvocatoria'),
        ),
    ]
