# Generated by Django 2.2.4 on 2019-08-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0016_auto_20190816_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oficio',
        ),
    ]
