# Generated by Django 2.2.4 on 2019-08-16 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0023_auto_20190816_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='lista',
        ),
    ]
