# Generated by Django 2.2.4 on 2019-08-14 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0009_auto_20190813_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de mantenimiento')),
                ('tipo', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], default='Preventivo', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('volumen', models.IntegerField(verbose_name='Volumen indicado en medidor (Litros)')),
                ('carnet', models.ImageField(upload_to='mantenimientos/%Y/%m/%d/', verbose_name='Carnet actualizado')),
                ('foto_inicio', models.ImageField(upload_to='mantenimientos/%Y/%m/%d/', verbose_name='Foto al iniciar el mantenimiento')),
                ('foto_fin', models.FileField(upload_to='mantenimientos/%Y/%m/%d/', verbose_name='Foto al finalizar el mantenimiento')),
                ('foto_medidor', models.FileField(blank=True, null=True, upload_to='mantenimientos/%Y/%m/%d/', verbose_name='Foto del medidor')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.Escuela')),
            ],
        ),
    ]
