# Generated by Django 2.2.4 on 2019-08-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='foto_fin',
            field=models.ImageField(upload_to='mantenimientos/%Y/%m/%d/', verbose_name='Foto al finalizar el mantenimiento'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='foto_medidor',
            field=models.ImageField(default='a', upload_to='mantenimientos/%Y/%m/%d/', verbose_name='Foto del medidor'),
        ),
    ]
