# Generated by Django 2.2.4 on 2019-08-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0006_auto_20190806_1446'),
        ('bebederos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaBebedero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns_mueble', models.CharField(blank=True, max_length=20, null=True)),
                ('no_trazabilidad', models.TextField(blank=True, null=True)),
                ('esta_en_campo', models.BooleanField(default=False)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.Escuela')),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebederos.Mueble')),
                ('sistema_potabilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bebederos.SistemaPotabilizador')),
            ],
        ),
    ]
