# Generated by Django 2.2.4 on 2019-08-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0002_sistemabebedero'),
    ]

    operations = [
        migrations.AddField(
            model_name='mueble',
            name='nivel_educativo',
            field=models.CharField(choices=[('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], default='Primaria', max_length=20),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='modelo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
