# Generated by Django 2.2.4 on 2019-08-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0003_auto_20190806_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='nivel_educativo',
            field=models.CharField(choices=[('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=20),
        ),
    ]
