# Generated by Django 2.2.4 on 2019-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0004_auto_20190806_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='modelo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
