# Generated by Django 2.2.4 on 2019-08-13 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0008_auto_20190813_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemabebedero',
            name='slug',
        ),
    ]
