# Generated by Django 2.2.4 on 2019-08-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0009_remove_sistemabebedero_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemabebedero',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
