# Generated by Django 2.2.4 on 2019-08-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0010_sistemabebedero_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='escuela',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escuelas.Escuela'),
        ),
    ]
