# Generated by Django 2.2.4 on 2019-08-16 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0011_auto_20190816_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemabebedero',
            name='escuela',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_sb', to='escuelas.Escuela'),
        ),
    ]
