# Generated by Django 2.2.4 on 2019-08-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0013_auto_20190816_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sistemabebedero',
            old_name='ns_mueble',
            new_name='num_serie_mueble',
        ),
        migrations.RemoveField(
            model_name='mueble',
            name='ficha_tecnica',
        ),
        migrations.RemoveField(
            model_name='mueble',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='sistemapotabilizador',
            name='ficha_tecnica',
        ),
        migrations.RemoveField(
            model_name='sistemapotabilizador',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
