# Generated by Django 2.2.4 on 2019-08-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='acta_entrega',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Acta de entrega'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='acta_funcionamiento',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Acta de Inicio de funcionamiento'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='acta_inicio_construccion',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Acta de inicio de construcción'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='acta_ubicacion',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Acta de ubicación de bebedero'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cedula_identificacion',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Cédula de identificación'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='convenio_concertacion',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Convenio de concertación de aplicación de recurso'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='distribucion_planta',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Distribución en planta'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='isometrico_instalacion',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Isometricos de instalaciones'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='levantamiento_instalacion',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Levantamiento de instalación'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='memoria_calculo_1',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Memoria de cálculo hidráulico'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='memoria_calculo_2',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Memoria de cálculo sanitario'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='memoria_calculo_3',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Memoria de cálculo eléctrico'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='plano_conjunto',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/%Y/%m/%d/', verbose_name='Plano de conjunto'),
        ),
    ]
