# Generated by Django 2.2.4 on 2019-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_auto_20190806_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='descripcion',
            field=models.CharField(choices=[('Antes', 'Antes'), ('Durante', 'Durante'), ('Despues', 'Despues')], max_length=10),
        ),
    ]
