# Generated by Django 2.2.4 on 2019-08-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_auto_20190813_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fotografia_antes_1',
            field=models.ImageField(blank=True, null=True, upload_to='fotografias/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fotografia_antes_2',
            field=models.ImageField(blank=True, null=True, upload_to='fotografias/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fotografia_despues_1',
            field=models.ImageField(blank=True, null=True, upload_to='fotografias/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fotografia_despues_2',
            field=models.ImageField(blank=True, null=True, upload_to='fotografias/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fotografia_duarnte_1',
            field=models.ImageField(blank=True, null=True, upload_to='fotografias/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fotografia_durante_2',
            field=models.ImageField(blank=True, null=True, upload_to='fotografias/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Fotografia',
        ),
    ]
