# Generated by Django 2.2.4 on 2019-08-16 23:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0026_auto_20190816_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('En espera', 'En espera'), ('Atendiendo', 'Atendiendo'), ('Solucionado', 'Solucionado'), ('No aplica', 'No aplica')], default='En espera', max_length=30)),
                ('prioridad', models.CharField(choices=[('Ninguna', 'Ninguna (Es una notificación)'), ('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10)),
                ('solucion', models.TextField(blank=True, null=True, verbose_name='Solución')),
                ('fecha_solucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de solucion')),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('evidencia_incidencia', models.ImageField(blank=True, null=True, upload_to='incidencias/%Y/%m/%d/', verbose_name='Evidencia de incidencia')),
                ('evidencia_solucion', models.ImageField(blank=True, null=True, upload_to='incidencias/%Y/%m/%d/', verbose_name='Evidencia de solución')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.Escuela')),
            ],
            options={
                'ordering': ['creacion'],
            },
        ),
    ]
